name: Flutter Desktop Build

on:
  push:
    branches: [ main, master ]
    paths:
      - 'lib/**'
      - 'android/**'
      - 'ios/**'
      - 'macos/**'
      - 'windows/**'
      - 'linux/**'
      - 'pubspec.yaml'
      - '.github/workflows/flutter-desktop.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'lib/**'
      - 'android/**'
      - 'ios/**'
      - 'macos/**'
      - 'windows/**'
      - 'linux/**'
      - 'pubspec.yaml'
      - '.github/workflows/flutter-desktop.yml'
  workflow_dispatch:

jobs:
  build-macos:
    name: Build Fuego Wallet (macOS)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Enable macOS desktop support
        run: flutter config --enable-macos-desktop

      - name: Download xfg-stark-cli
        run: |
          curl -L -o xfg-stark-cli "https://github.com/ColinRitman/xfgwin/releases/download/v0.8.8/xfg-stark-cli-macos"
          chmod +x xfg-stark-cli
          mkdir -p assets/bin
          mv xfg-stark-cli assets/bin/

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS desktop app
        run: flutter build macos --release

      - name: Create app archive
        run: |
          cd build/macos/Build/Products/Release
          zip -r Fuego-Wallet-macOS.zip "fuego_wallet.app"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fuego-wallet-macos
          path: build/macos/Build/Products/Release/Fuego-Wallet-macOS.zip
          retention-days: 30

  build-windows:
    name: Build Fuego Wallet (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      - name: Download xfg-stark-cli
        run: |
          curl -L -o xfg-stark-cli.exe "https://github.com/ColinRitman/xfgwin/releases/download/v0.8.8/xfg-stark-cli-windows.exe"
          mkdir -p assets\bin
          mv xfg-stark-cli.exe assets\bin\

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows desktop app
        run: flutter build windows --release

      - name: Create app archive
        run: |
          if (Test-Path "build\windows\runner\Release") {
            cd build\windows\runner\Release
            Compress-Archive -Path * -DestinationPath ..\..\..\..\Fuego-Wallet-Windows.zip
          } elseif (Test-Path "build\windows\x64\runner\Release") {
            cd build\windows\x64\runner\Release
            Compress-Archive -Path * -DestinationPath ..\..\..\..\..\Fuego-Wallet-Windows.zip
          } else {
            Get-ChildItem build -Recurse | Where-Object { $_.Name -like "*.exe" } | Select-Object -First 1 | ForEach-Object { Compress-Archive -Path $_.DirectoryName -DestinationPath "Fuego-Wallet-Windows.zip" }
          }

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fuego-wallet-windows
          path: Fuego-Wallet-Windows.zip
          retention-days: 30

  build-linux:
    name: Build Fuego Wallet (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Download xfg-stark-cli
        run: |
          curl -L -o xfg-stark-cli "https://github.com/ColinRitman/xfgwin/releases/download/v0.8.8/xfg-stark-cli-linux"
          chmod +x xfg-stark-cli
          mkdir -p assets/bin
          mv xfg-stark-cli assets/bin/

      - name: Enable Linux desktop support
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libsecret-1-dev
          flutter config --enable-linux-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Linux desktop app
        run: flutter build linux --release

      - name: Create app archive
        run: |
          cd build/linux/x64/release/bundle
          tar -czf Fuego-Wallet-Linux.tar.gz *

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fuego-wallet-linux
          path: build/linux/x64/release/bundle/Fuego-Wallet-Linux.tar.gz
          retention-days: 30
